version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: shareit_postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d shareit -U username"]
      interval: 30s
      timeout: 10s
      retries: 5

  app:
    build: .
    container_name: shareit_app
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/shareit
      SPRING_DATASOURCE_USERNAME: username
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_JPA_HIBERNATE_DDL_AUTO: none
    ports:
      - "8080:8080"

volumes:
  postgres_data:
