version: '3.8'

services:
  db:
    image: postgres:alpine
    container_name: shareit_postgres
    environment:
      POSTGRES_DB: shareit
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U shareit_user"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:
